"use client";
// Styles
import "../styles/main.scss";

// Font
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Redux
import { store } from "@/redux/store";
import { Provider } from "react-redux";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
}
